# src: https://www.honlsoft.com/blog/2022-08-20-publishing-nuget-packages-through-github-actions

name: Publish Nuget Package

on:
  workflow_dispatch:
  push:
    tags: [ 'v*.*.*' ]

env:
  VERSION: 0.0.1-default
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Version Variable
      if: ${{ github.ref_type == 'tag' }}
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release /p:Version=$VERSION
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
    - name: pack nuget packages
      run: dotnet pack --output nupkgs --no-restore --no-build -c Release /p:PackageVersion=$VERSION
    - name: manual file check
      run: ls
    - name: upload nuget package
      if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json